global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'distributed-cache'
    static_configs:
      - targets: ['localhost:8081', 'localhost:8082', 'localhost:8083'] # List all cache instances here
